---
- hosts: all
  sudo: true
  tasks:
    - name: Install Java 1.7
      yum: name=java-1.7.0-openjdk state=present
    - name: Download Tomcat
      get_url: url=http://mirrors.viethosting.vn/apache/tomcat/tomcat-7/v7.0.65/bin/apache-tomcat-7.0.65.tar.gz dest=/opt/apache-tomcat-7.0.65.tar.gz
    - name: add group "tomcat"
      group: name=tomcat
    - name: add user "tomcat"
      user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
      sudo: True
    - name: Download Tomcat
      get_url: url=http://mirrors.viethosting.vn/apache/tomcat/tomcat-7/v7.0.65/bin/apache-tomcat-7.0.65.tar.gz dest=/opt/apache-tomcat-7.0.65.tar.gz
    - name: Extract archive
      command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-7.0.65.tar.gz -C /opt/ creates=/opt/apache-tomcat-7.0.65
    - name: Symlink install directory
      file: src=/opt/apache-tomcat-7.0.65 path=/usr/share/tomcat state=link
    - name: Change ownership of Tomcat installation
      file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes
    - name: install mysql
      yum: name=mysql-server state=present
    - name: Check tomcat file
      stat: path=/etc/init.d/tomcat
      register: st
    - name: Copy tomcat file
      copy: src=tomcat/tomcat dest=/etc/init.d
      when: st.stat.exists == false
    - name: Set permission for tomcat
      file: path=/etc/init.d/tomcat mode=755
    - name: Start tomcat
      service: name=tomcat state=started enabled=yes
    - name: Check file war
      stat: path=/usr/share/tomcat/webapps/TestWebApp-0.0.1-SNAPSHOT.war
      register: stwar
    - name: Delete old file war
      command: rm /usr/share/tomcat/webapps/TestWebApp-0.0.1-SNAPSHOT.war
      when: stwar.stat.exists == true
    - name: Copy war file
      copy: src=target/TestWebApp-0.0.1-SNAPSHOT.war dest=/usr/share/tomcat/webapps
    - name: Start tomcat
      service: name=tomcat state=restarted
    